name: Script Daily Run - Sheet to WhatsApp

on:
  schedule:
    - cron: "30 3 * * *"  # 9:00 AM IST
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 3. Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pillow gspread oauth2client

      # 4. Install Chrome & ChromeDriver
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver
          # Add chromedriver to PATH
          export PATH=$PATH:/usr/lib/chromium-browser/
      
      # 5. Set up Google credentials secret
      - name: Set Google credentials
        run: echo "${{ secrets.GSPREAD_KEY }}" > /tmp/credentials.json
        # Export env for script
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GSPREAD_KEY }}

      # 6. Run the Python script
      - name: Run activity report script
        run: python final_activity_report_share.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GSPREAD_KEY }}
