name: Daily Activity Report

on:
  schedule:
    - cron: "0 9 * * *"   # Runs daily at 9:00 AM UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client selenium

      - name: Set up Chrome
        uses: nanasess/setup-chromedriver@v1
        with:
          chrome-version: latest

      - name: Run Python script
        env:
          GSPREAD_KEY: ${{ secrets.GSPREAD_KEY }}
        run: python final_activity_report_share.py

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
          name: activity-screenshots
          path: /tmp/screenshot_*.png
