name: Script Daily Run - Sheet to Wsp

on:
  schedule:
    - cron: "30 3 * * *"  # 9:00 AM IST
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pillow gspread oauth2client

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: 'latest'

      - name: Configure gspread credentials
        run: |
          echo "${{ secrets.GSPREAD_KEY }}" > credentials.json

      - name: Run script
        run: python final_activity_report_share.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json
