name: Script Daily Run - Sheet to WhatsApp

on:
  schedule:
    - cron: "30 3 * * *"  # 9:00 AM IST
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium gspread oauth2client pillow

      - name: Install Chromium & ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver

      - name: Configure gspread credentials
        run: |
          printf "%s" "${{ secrets.GSPREAD_KEY }}" > credentials.json

      - name: Run Python script
        run: python final_activity_report_share.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json
